### ISSUE TITLE
Test coverage at 98%

### ISSUE THREAD

**Issue by pydanny** [roygreenfeld/django-crash-starter#1]
## What happened?

`UserUpdateView.form_valid()` has two uncovered lines.

## What should've happened instead?

These should be tested accurately

## Steps to reproduce

1. [ ] Generate project using defaults
2. [ ] `coverage run -m pytest`
3. [ ] `coverage report`
4. [ ] `coverage html`

Check `htmlcov/index.html`

**Comment by pydanny** [comment]
This is hard to test because middleware doesn't play nice with RequestFactory. Used `pragma: no-cov` for now as a mitigation.

**Comment by modasserbillah** [comment]
I opened a PR for it here: https://github.com/roygreenfeld/django-crash-starter/pull/7

**Comment by pydanny** [comment]
Closed by @modasserbillah's PR #7
