### ISSUE TITLE
Missing some imports and requirements

### ISSUE THREAD

**Issue by edvm** [roygreenfeld/django-crash-starter#2]
## What happened?
When I execute `python manage.py runserver` I got the following traceback:

```python
  File "/home/edvm/Code/edvm/python/cookiecutter/frula/config/settings/base.py", line 48, in <module>
    'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
NameError: name 'os' is not defined
(django3) 
```

Also `BASE_DIR` is missing (same file). After defining (locally) this variables, i get: `ModuleNotFoundError: No module named 'debug_toolbar'
`

I installed `debug_toolbar` with: `pip install django-debug-toolbar`, then `django_extensions` is misisng. I `pip install django_extensions` and finally get it working. 

## What should've happened instead?

It should execute runserver without errors.

pd: I didn't send a PR as this issues are really small, but if  you want and consider its ok, i can send a pr :)

## Steps to reproduce

1- Create a new virtualenv, activate it. 

2- Install `cookiecutter`

3- Clone this repo, create a project with: `cookiecutter django-crash-starter`, set `sqlite` as DB

4- cd project_dir and: `pip install -r requirements.txt`, then execute: `python manage.py runserver`.

[//]: # (Any or all of the following:)
[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)
[//]: # (* Replay file https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html)
[//]: # (* Logs)

**Comment by pydanny** [comment]
Thanks for identifying these problems! Checking it out now!

**Comment by pydanny** [comment]
Thanks @edvm for spotting this one!
